INSERT INTO Question (question_title, option1, option2, option3, option4, right_answer, difficulty_level, category, chose)
VALUES
    ('What is a class in Java?', 'A function', 'An object', 'A data structure', 'A loop', 2, 'Easy', 'java', -1),
    ('What does OOP stand for?', 'Object-Oriented Programming', 'Object Ordering Process', 'Operating Overloaded Pointers', 'Order of Operations', 1, 'Easy', 'java', -1),
    ('What is a list in Python?', 'A type of loop', 'A built-in function', 'A data structure', 'An object',3 , 'Easy', 'python', -1),
    ('Which data structure uses First-In-First-Out (FIFO, -1) order?', 'Stack', 'Queue', 'Array', 'LinkedList', 2, 'Medium', 'python', -1),
    ('What is a constructor?', 'A member of a class', 'A loop in Python', 'A data type', 'A special method', 4, 'Medium', 'java', -1),
    ('Which sorting algorithm has the worst-case time complexity of O(n^2, -1)?', 'Merge Sort', 'Quick Sort', 'Insertion Sort', 'Bubble Sort', 4, 'Hard', 'python', -1),
    ('In Java, what is used to create an instance of a class?', 'Class', 'Method', 'Object', 'Constructor', 4, 'Easy', 'java', -1),
    ('Which keyword is used to define a variable that won’t be reassigned?', 'static', 'final', 'constant', 'immutable', 2, 'Easy', 'java', -1),
    ('What is the output of 4 ^ 3 in Python?', '7', '64', '81', '12', 2, 'Easy', 'python', -1),
    ('What does the term "polymorphism" refer to in programming?', 'Using multiple inheritance', 'Ability to take multiple forms', 'Manipulating data', 'Using multiple programming languages', 2, 'Medium', 'java', -1),
    ('What is the purpose of the "self" parameter in Python class methods?', 'It refers to the current instance of the class', 'It is used to call parent class methods', 'It is a keyword for loops', 'It is a data type', 1, 'Medium', 'python', -1),
    ('Which of the following is not a primitive data type in Java?', 'int', 'boolean', 'char', 'string', 4, 'Medium', 'java', -1),
    ('What is the time complexity of a binary search?', 'O(n, -1)', 'O(log n, -1)', 'O(n^2, -1)', 'O(1, -1)', 2, 'Medium', 'python', -1),
    ('What keyword is used to inherit a class in Python?', 'extends', 'inherits', 'super', 'class', 4, 'Easy', 'python', -1),
    ('Which type of loop is ideal for situations where the number of iterations is known?', 'for loop', 'while loop', 'do-while loop', 'until loop', 1, 'Easy', 'java', -1),
    ('What is the purpose of "import" in Python?', 'To export data', 'To create a backup', 'To include external modules', 'To print output', 3, 'Easy', 'python', -1),
    ('In Java, which access modifier provides the widest visibility?', 'public', 'private', 'protected', 'package-private', 1, 'Easy', 'java', -1),
('What is a lambda function in Python?', 'A function that uses the "lambda" keyword', 'A function with multiple return values', 'A function with no parameters', 'An anonymous inline function', 4, 'Medium', 'python', -1),
('What is a linked list?', 'A type of array', 'A linear data structure', 'A collection of objects', 'A group of classes', 2, 'Medium', 'java', -1),
('Which operator is used to concatenate strings in Python?', '&', '+', '*', '++', 2, 'Easy', 'python', -1),
('What does JVM stand for?', 'Java Virtual Machine', 'Just Virtual Memory', 'JavaScript Virtual Machine', 'Java Version Manager', 1, 'Easy', 'java', -1),
('In Python, what is the main difference between a tuple and a list?', 'Tuples are mutable, lists are not', 'Lists are ordered, tuples are not', 'Tuples can store mixed data types, lists cannot', 'Lists have a fixed size, tuples do not', 3, 'Medium', 'python', -1),
('What is the purpose of the "finally" block in a try-catch-finally statement?', 'To handle exceptions', 'To define a fallback value', 'To execute code regardless of exceptions', 'To terminate the program', 3, 'Medium', 'java', -1),
('What is a dictionary in Python?', 'A sorted collection of elements', 'A data structure used for searching', 'An ordered sequence of elements', 'A key-value store', 4, 'Easy', 'python', -1),
('Which keyword is used to define a subclass in Java?', 'implements', 'extends', 'inherits', 'subclass', 2, 'Easy', 'java', -1),
('What is the purpose of the "pass" statement in Python?', 'To stop the execution of a loop', 'To indicate an empty code block', 'To raise an exception', 'To terminate the program', 2, 'Easy', 'python', -1);